/*
STATUS: BETA TO V1.3.0
RULES:
- DO NOT SELL THIS SCRIPT!!
- THIS SCRIPT IS 100% FREE, DO NOT SELL IT!!!
- DO NOT REUPLOAD OR SHARE IT TO CHANNELS/ETC!!

IF YOU'RE A USER, THERE'S PROBABLY NOTHING HERE YOU NEED TO CHANGE.
IF YOU UNDERSTAND THE BOT, IT'S FINE — OTHERWISE ERRORS ARE YOUR RESPONSIBILITY.

THIS SCRIPT IS 100% MAINTAINED BY XZIYY

JOIN TREPLEX CODERVERSE CHANNEL:
https://whatsapp.com/channel/0029VbAUashAu3aYDTjzqq0v

LEARN ABOUT THIS SCRIPT?:
https://chat.whatsapp.com/I3FFi9rm3zwDxnhMJDAnPd
*/
